CREATE TABLE CAFE_OPTION (
	CUP_SIZE VARCHAR2(1) CHECK (CUP_SIZE = 'S' OR CUP_SIZE = 'M' OR CUP_SIZE = 'L'),
	ADD_SHOT NUMBER,
	ADD_SYRUP NUMBER,
	HOT_ICE VARCHAR2(5) CHECK (HOT_ICE = 'HOT' OR HOT_ICE = 'ICE')
);
--ALTER TABLE CAFE_OPTION
--MODIFY MENU_NUMBER PRIMARY KEY;
--
--DESC CAFE_OPTION;
DROP TABLE CAFE_OPTION;

/* 옵션별 가격 테이블 만들기 */
CREATE TABLE OPTION_PRICE (
    SIZE_PRICE      NUMBER,
    SHOT_PRICE      NUMBER,
    SYRUP_PRICE     NUMBER  
);    

SELECT * FROM OPTION_PRICE;
DROP TABLE OPTION_PRICE;
    

    