/* 메뉴 테이블 만들기 */
CREATE TABLE MENU_INFO (
/*메뉴 번호*/       MENU_NUMBER  NUMBER PRIMARY KEY, -- 기본키
/*메뉴 구분*/       MENU_TYPE    VARCHAR2(20) CHECK (MENU_TYPE = 'COFFEE' OR MENU_TYPE = 'NON-COFFEE'),
/*메뉴 이름*/       MENU_NAME    VARCHAR2(20),
/*메뉴 금액*/       MENU_PRICE   NUMBER
);

-- COFFEE
INSERT INTO MENU_INFO VALUES (1001, 'COFFEE', '에스프레소', 2500);
INSERT INTO MENU_INFO VALUES (1002, 'COFFEE', '아메리카노', 4000);
INSERT INTO MENU_INFO VALUES (1003, 'COFFEE', '라떼', 5000);
INSERT INTO MENU_INFO VALUES (1004, 'COFFEE', '카페모카', 5500);

-- NON-COFFEE
INSERT INTO MENU_INFO VALUES (2001, 'NON-COFFEE', '초코우유', 2500);
INSERT INTO MENU_INFO VALUES (2002, 'NON-COFFEE', '녹차', 2500);
INSERT INTO MENU_INFO VALUES (2003, 'NON-COFFEE', '홍차', 2500);
INSERT INTO MENU_INFO VALUES (2004, 'NON-COFFEE', '밀크티', 2500);

SELECT * FROM MENU_INFO;
DROP TABLE MENU_INFO;