/* 고객 주문 테이블 만들기 */
CREATE TABLE ORDER_INFO(
/* 오늘 날짜 */ DATE_TODAY DATE DEFAULT SYSDATE,
/* 고객 이름 */ CUSTOMER    VARCHAR2(20) NOT NULL,
/* 메뉴 선택 */ MNO         NUMBER,
/* 옵션 선택 */ OPTION_NAME VARCHAR2(20),
/* 샷 추가 */ ADD_SHOT NUMBER
);

INSERT INTO ORDER_INFO (CUSTOMER, MNO, OPTION_NAME, ADD_SHOT)  VALUES ('조혜경', 1001, 'S', 1);
INSERT INTO ORDER_INFO (CUSTOMER, MNO, OPTION_NAME, ADD_SHOT)  VALUES ('박하늘', 2001, 'M', 2);
INSERT INTO ORDER_INFO (CUSTOMER, MNO, OPTION_NAME, ADD_SHOT)  VALUES ('이주연', 2002, 'L', 1);
INSERT INTO ORDER_INFO (CUSTOMER, MNO, OPTION_NAME, ADD_SHOT)  VALUES ('우혜정', 1004, 'S', 3);
INSERT INTO ORDER_INFO (CUSTOMER, MNO, OPTION_NAME, ADD_SHOT)  VALUES ('정재이', 2003, 'L', 2);
INSERT INTO ORDER_INFO (CUSTOMER, MNO, OPTION_NAME, ADD_SHOT)  VALUES ('박하린', 2004, 'M', 0);
INSERT INTO ORDER_INFO (CUSTOMER, MNO, OPTION_NAME, ADD_SHOT)  VALUES ('조혜경', 1001, 'S', 3);

SELECT * FROM ORDER_INFO;
DROP TABLE ORDER_INFO;


/* 주문 금액 계산 테이블 만들기 */

CREATE TABLE ORDER_PRICE
        MENU_NO NUMBER REFERENCES      





    AS SELECT O.CUSTOMER, O.MNO, O.OPTION_NAME, M.MPRICE, O.SIZE_PRICE, O.ADD_SHOT, O.ADD_SHOT * 400 SHOT_PRICE,
                M.MPRICE+O.SIZE_PRICE+(O.ADD_SHOT * 400) "토탈"
            
        FROM MENU_INFO M JOIN ( SELECT I.CUSTOMER, I.MNO, I.OPTION_NAME, P.SIZE_PRICE, I.ADD_SHOT
                                FROM ORDER_INFO I, OPTION_INFO P
                                WHERE I.OPTION_NAME = P.CUP_SIZE) O
        ON O.MNO = M.MNO;



SELECT * FROM CUSTOMER_PRICE;
DROP TABLE CUSTOMER_PRICE;







--SELECT O.CUP_SIZE, O.ADD_SHOT, O.OPT_PRICE, O.HOT_ICE_NONE
--FROM CAFE_OPTION O INNER JOIN MENU_INFO I
--    ON O.ADD_SHOT = I.MNO
--    WHERE I.MNAME = '아메리카노';    
--    
--INSERT INTO MENU_INFO (MNAME)
--    VALUES ('아메리카노');








